import { Ghost, Flame, Share2, Stethoscope } from 'lucide-react';
import { useState } from 'react';

interface WelcomeScreenProps {
  onStartGame: () => void;
  isLoading: boolean;
  onShowHealthCheck?: () => void;
}

export function WelcomeScreen({ onStartGame, isLoading, onShowHealthCheck }: WelcomeScreenProps) {
  const [copied, setCopied] = useState(false);

  const handleShare = () => {
    const url = window.location.href;
    const text = `Dare to enter Echo Manor? I'm investigating a murder mystery generated by AI. Join me! #EchoManor ${url}`;
    
    // Try navigator.share first (mobile), fallback to clipboard
    if (navigator.share) {
      navigator.share({
        title: 'Echo Manor Mysteries',
        text: text,
        url: url
      }).catch(() => {
        // If share fails, fallback to clipboard
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      });
    } else {
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 flex items-center justify-center p-4 relative overflow-hidden">
      {/* Fog Overlay */}
      <div className="fog-overlay" />

      {/* Atmospheric Background Elements */}
      <div className="absolute inset-0 pointer-events-none">
        {/* Radial gradient vignette */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,transparent_0%,rgba(0,0,0,0.6)_100%)]" />

        {/* Floating candles */}
        <div className="absolute top-20 left-[15%] animate-float" style={{ animationDelay: '0s' }}>
          <Flame className="w-6 h-6 text-amber-500/60 animate-candle" />
        </div>
        <div className="absolute top-32 right-[20%] animate-float" style={{ animationDelay: '1s' }}>
          <Flame className="w-5 h-5 text-amber-500/50 animate-candle" style={{ animationDelay: '0.5s' }} />
        </div>
        <div className="absolute bottom-40 left-[25%] animate-float" style={{ animationDelay: '2s' }}>
          <Flame className="w-4 h-4 text-amber-500/40 animate-candle" style={{ animationDelay: '1s' }} />
        </div>
        <div className="absolute bottom-32 right-[15%] animate-float" style={{ animationDelay: '1.5s' }}>
          <Flame className="w-5 h-5 text-amber-500/50 animate-candle" style={{ animationDelay: '0.3s' }} />
        </div>
      </div>

      <div className="max-w-2xl w-full text-center space-y-8 relative z-10">
        {/* Animated Ghost Icon */}
        <div className="flex justify-center mb-8 animate-float">
          <div className="relative">
            <Ghost className="w-28 h-28 text-red-800 animate-blood-glow rounded-full p-4" />
            <div className="absolute inset-0 bg-red-900/20 blur-2xl rounded-full" />
          </div>
        </div>

        {/* Title with Dramatic Reveal */}
        <div className="space-y-2 animate-dramatic-reveal">
          <h1 className="text-7xl font-serif text-slate-100 tracking-wider text-glow-blood">
            Echo Manor
          </h1>
          <h2 className="text-4xl font-serif text-red-700 italic tracking-wide">
            Mysteries
          </h2>
        </div>

        <div className="flex flex-col items-center gap-6 animate-fadeIn" style={{ animationDelay: '0.6s' }}>
          <button
            onClick={onStartGame}
            disabled={isLoading}
            className="group relative px-12 py-4 bg-transparent overflow-hidden rounded-lg transition-all duration-300
                       hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-red-900 to-slate-900 opacity-80 group-hover:opacity-100 transition-opacity" />
            <div className="absolute inset-0 border border-red-500/30 rounded-lg group-hover:border-red-500/60 transition-colors" />

            <span className="relative z-10 font-serif text-2xl text-slate-200 tracking-widest group-hover:text-white flex items-center gap-3">
              {isLoading ? (
                <>
                  <Flame className="w-6 h-6 animate-bounce" />
                  Summoning...
                </>
              ) : (
                <>
                  <span>Enter the Manor</span>
                  <Ghost className="w-6 h-6 opacity-0 group-hover:opacity-100 transition-opacity translate-x-[-10px] group-hover:translate-x-0" />
                </>
              )}
            </span>
          </button>

          <button
            onClick={handleShare}
            className="group text-slate-500 hover:text-slate-300 transition-colors flex items-center gap-2 text-sm uppercase tracking-widest relative"
            title="Copy link to share with friends"
          >
            <Share2 className="w-4 h-4 group-hover:animate-bounce" />
            <span className={copied ? "text-green-400" : ""}>
              {copied ? "Link Copied!" : "Share the Mystery"}
            </span>
          </button>

          {onShowHealthCheck && (
            <button
              onClick={onShowHealthCheck}
              className="text-slate-600 hover:text-slate-400 transition-colors flex items-center gap-2 text-xs uppercase tracking-widest"
              title="Check system configuration"
            >
              <Stethoscope className="w-3 h-3" />
              Diagnostics
            </button>
          )}
        </div>

        {/* Tagline */}
        <p
          className="text-slate-500 text-sm italic animate-fadeIn opacity-0"
          style={{ animationDelay: '0.7s', animationFillMode: 'forwards' }}
        >
          Each mystery is uniquely generated by AI - no two cases are alike.
        </p>

        {/* Decorative Corners */}
        <div className="ornament">
          <div className="ornament-corner top-left" style={{ position: 'fixed' }} />
          <div className="ornament-corner top-right" style={{ position: 'fixed' }} />
          <div className="ornament-corner bottom-left" style={{ position: 'fixed' }} />
          <div className="ornament-corner bottom-right" style={{ position: 'fixed' }} />
        </div>
      </div>
    </div >
  );
}
